### ISSUE TITLE
Is there an alpha stage version?

### ISSUE THREAD

**Issue by brtn** [workflowy/desktop#1]
I hate the fact that current desktop app is a chrome app. It is not that I don't have chrome, but it is a pain to try to switch apps as macos sees workflowy and chrome as the same app although 2 different app icons show on the switcher.

Even if you don't have autoupdate and other super things ready yet, if you have an initial wrap of the web version, could you provide a link or push up here? It would change my life :D

Thanks for the great app btw 👍

**Comment by jessep** [comment]
I actually did a test release, which you can check out. I only did the
build for mac, cause that's what I have right now and am still just figuing
this out:
https://github.com/workflowy/workflowy-electron-app-releases/releases

**Comment by brtn** [comment]
Ah, did not know the Releases section of Github :) Thanks, I will try this one.

**Comment by brtn** [comment]
For me, this is perfect :D
